jobs:
  - name: unit test
    engine:
      docker: alpine
    steps:
      - echo hello
      - echo world

  - name: regression test
    engine:
      docker: fedora
    steps:
      - |
        echo multiline
        echo steps
      - echo single step
    when:
      branch: \startsWith feat-

  - name: integration test
    engine:
      vm: ubuntu
    steps:
      - echo lorem
      - echo ipsum
    when:
      branch:
        - master
        - dev

  - name: deploy
    engine:
      vm: ubuntu
    steps: |
      echo hey
      echo there
    when:
      tag: \semver
